- applicableMode: CAR
  type: SLIDER
  key: carReluctance
  default: 3
  low: 0
  high: 5
  step: 0.1
  label: Car Reluctance
  labelLow: More Driving
  labelHigh: More Transit
- applicableMode: BICYCLE
  type: SLIDER
  key: bikeReluctance
  default: 2
  low: 0
  high: 5
  step: 0.1
  label: Bike Reluctance
  labelLow: More Biking
  labelHigh: More Transit
- applicableMode: WALK
  type: SLIDER
  key: walkReluctance
  default: 2
  low: 0
  high: 5
  step: 0.1
  label: Walk Reluctance
  labelLow: More Walking
  labelHigh: More Transit
- applicableMode: BICYCLE
  type: CHECKBOX_ADD_MODE
  key: allowBikeRental
  default: true
  addMode:
    mode: BICYCLE
    qualifier: RENT
  label: Enable Bike Rental
- applicableMode: TRANSIT
  type: CHECKBOX
  key: wheelchair
  default: false
  label: Use Accessible Routing
