- applicableMode: TRANSIT
  type: SLIDER
  key: walkReluctance
  default: 0
  low: 0
  high: 5
  step: 0.1
  label: Walk Reluctance
  labelLow: More Walking
  labelHigh: More Transit
- applicableMode: BICYCLE
  type: CHECKBOX_ADD_MODE
  key: enableBikeshare
  default: true
  addMode:
    mode: BICYCLE
    qualifier: RENT
  label: Enable Bike Rental
- applicableMode: TRANSIT
  type: DROPDOWN
  key: busColor
  default: BLUE
  label: Preferred Bus Color
  options:
    - text: Red
      value: RED
    - text: Blue
      value: BLUE
    - text: Green
      value: GREEN
