- applicableMode: CAR
  graphQLQueryParam: true
  type: SLIDER
  key: carReluctance
  default: 3
  low: 0
  high: 5
  step: 0.1
- applicableMode: BICYCLE
  graphQLQueryParam: true
  type: SLIDER
  key: bikeReluctance
  default: 2
  low: 0
  high: 5
  step: 0.1
- applicableMode: WALK
  graphQLQueryParam: true
  type: SLIDER
  key: walkReluctance
  default: 2
  low: 0
  high: 5
  step: 0.1
- applicableMode: BICYCLE
  type: CHECKBOX
  key: allowBikeRental
  default: true
  addTransportMode:
    mode: BICYCLE
    qualifier: RENT
- applicableMode: TRANSIT
  type: CHECKBOX
  key: wheelchair
  default: false
  label: Use Accessible Routing
- applicableMode: TRANSIT
  type: CHECKBOX
  key: addBus
  default: true
  addTransportMode:
    mode: BUS
- applicableMode: TRANSIT
  type: CHECKBOX
  key: addRail
  default: true
  addTransportMode:
    mode: RAIL
- applicableMode: TRANSIT
  type: CHECKBOX
  key: addSubway
  default: true
  addTransportMode:
    mode: SUBWAY
- applicableMode: TRANSIT
  type: CHECKBOX
  key: addTram
  default: true
  addTransportMode:
    mode: TRAM
