- applicableMode: CAR
  default: 3
  graphQLQueryParam: true
  high: 5
  inverseKey: carReluctance
  key: carTolerance
  low: 0
  step: 0.1
  type: SLIDER
- applicableMode: BICYCLE
  default: 2
  graphQLQueryParam: true
  high: 5
  inverseKey: bikeReluctance
  key: bikeTolerance
  low: 0
  step: 0.1
  type: SLIDER
- applicableMode: WALK
  default: 2
  graphQLQueryParam: true
  high: 5
  inverseKey: walkReluctance
  key: walkTolerance
  low: 0
  step: 0.1
  type: SLIDER
