name: Node.js CI

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next
      - next-major
      # This is an attempt to match semantic-release's branch pattern using
      # GitHub Actions' regex-like matching
      # See https://semantic-release.gitbook.io/semantic-release/v/beta/usage/configuration#branches
      # See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"
      - "[0-9]+.x"
  pull_request:

jobs:
  test-build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install npm packages using cache
        uses: bahmutov/npm-install@v1
      - name: Lint code
        run: yarn lint:js
      #    - name: Lint styles
      #     run: yarn lint:styles
      ##  - name: Type check
      #   run: yarn typescript
      #  - name: Run tests
      #   run: yarn unit
      # - name: Run a11y tests
      #   run: yarn a11y-test

      # at this point, the build is successful
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
